//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFreshStoreCore.Model.Context
{
    using System;
    using System.Collections.Generic;

    public partial class DeliveryMan
    {
        public DeliveryMan()
        {
            this.MasterDepotDeliveryMen = new HashSet<MasterDepotDeliveryMan>();
            this.AssignOrders = new HashSet<AssignOrder>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<long> UserId { get; set; }
        public string NID { get; set; }
        public Nullable<long> ThanaId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ImageUrl { get; set; }

        public virtual Thana Thana { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<MasterDepotDeliveryMan> MasterDepotDeliveryMen { get; set; }
        public virtual ICollection<AssignOrder> AssignOrders { get; set; }
    }
}
