//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFreshStoreCore.Model.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class FreshContext : DbContext
    {
        public FreshContext()
            : base("name=FreshContext")
        {
            Configuration.LazyLoadingEnabled = false;
            Configuration.ProxyCreationEnabled = false;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public DbSet<Brand> Brands { get; set; }
        public DbSet<Cart> Carts { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<CorporateContract> CorporateContracts { get; set; }
        public DbSet<CorporateDepartment> CorporateDepartments { get; set; }
        public DbSet<CorporateDesignation> CorporateDesignations { get; set; }
        public DbSet<CorporateUser> CorporateUsers { get; set; }
        public DbSet<Coupon> Coupons { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<DeliveryMan> DeliveryMen { get; set; }
        public DbSet<Distributor> Distributors { get; set; }
        public DbSet<DistributorProductLine> DistributorProductLines { get; set; }
        public DbSet<District> Districts { get; set; }
        public DbSet<Location> Locations { get; set; }
        public DbSet<MasterDepot> MasterDepots { get; set; }
        public DbSet<MasterDepotDeliveryMan> MasterDepotDeliveryMen { get; set; }
        public DbSet<MasterDepotProductLine> MasterDepotProductLines { get; set; }
        public DbSet<MeghnaDepartment> MeghnaDepartments { get; set; }
        public DbSet<MeghnaDesignation> MeghnaDesignations { get; set; }
        public DbSet<MeghnaUser> MeghnaUsers { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<OrderDetail> OrderDetails { get; set; }
        public DbSet<OrderHistory> OrderHistories { get; set; }
        public DbSet<OrderReject> OrderRejects { get; set; }
        public DbSet<OrderState> OrderStates { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<ProductDiscount> ProductDiscounts { get; set; }
        public DbSet<ProductImage> ProductImages { get; set; }
        public DbSet<ProductLine> ProductLines { get; set; }
        public DbSet<ProductLineDetail> ProductLineDetails { get; set; }
        public DbSet<ProductType> ProductTypes { get; set; }
        public DbSet<ProductUnit> ProductUnits { get; set; }
        public DbSet<ProductUnitPrice> ProductUnitPrices { get; set; }
        public DbSet<Rating> Ratings { get; set; }
        public DbSet<Subscriber> Subscribers { get; set; }
        public DbSet<Thana> Thanas { get; set; }
        public DbSet<ThanaWiseMasterDepot> ThanaWiseMasterDepots { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserDiscount> UserDiscounts { get; set; }
        public DbSet<UserType> UserTypes { get; set; }
        public DbSet<WishList> WishLists { get; set; }
        public DbSet<AssignOrder> AssignOrders { get; set; }
        public DbSet<FAQ> FAQs { get; set; }
        public DbSet<Configuration> Configurations { get; set; }
        public DbSet<DeliveryCharge> DeliveryCharges { get; set; }
        public DbSet<PaymentDetail> PaymentDetails { get; set; }
        public DbSet<LPGComboDiscount> LPGComboDiscounts { get; set; }
    }
}
