//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFreshStoreCore.Model.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderHistory
    {
        public long Id { get; set; }
        public long OrderId { get; set; }
        public long OrderStateId { get; set; }
        public System.DateTime OrderStateChangedOn { get; set; }
        public Nullable<long> OrderStateChangedBy { get; set; }
        public string Remarks { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual OrderState OrderState { get; set; }
        public virtual User User { get; set; }
    }
}
